import dotenv from "dotenv";
dotenv.config();
export const PORT = process.env.PORT || 3000;
export const DATABASE_URL = process.env.DATABASE_URL;
export const JWT_SECRET = process.env.JWT_SECRET;
export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
export const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
export const GOOGLE_CALLBACK_URL = process.env.GOOGLE_CALLBACK_URL ;
export const CLIENT_URL = process.env.CLIENT_URL ;
export const SERVER_URL = process.env.SERVER_URL;
export const NODE_ENV = process.env.NODE_ENV || "development";
